substitutions:
  _REPO_NAME: my-profile-website
  _LOCATION: northamerica-northeast2
  _IMAGE_NAME: digital-twin-api-service
  _SERVICE_NAME: digital-twin-api-service

steps:
  # STEP 1: Build the container image using your Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    env:
        - 'DOCKER_BUILDKIT=0'
    args: 
      - 'build'
      - '-t'
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '.'

  # STEP 2: Push the image to your Artifact Registry warehouse
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: 
      - 'push'
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'

  # STEP 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: 'gcloud'
    args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
    - '--region'
    - '${_LOCATION}'
    - '--allow-unauthenticated'
    - '--max-instances'
    - '2'
    - '--set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,CHROMA_SERVER_AUTH_CREDENTIALS=CHROMA_SERVER_AUTH_CREDENTIALS:latest,REDIS_PASSWORD=REDIS_PASSWORD:latest'
    - '--vpc-connector=kindnus-run-vpc-connector'
    - '--vpc-egress=all'
    - '--ingress=internal'





options:
  logging: CLOUD_LOGGING_ONLY
