services:
  ###### using chromadb but reality is this will be a prod ready db such as weaviate or pinecone 
  chromadb:
    # Pinning by Image + Tag + Digest
    image: chromadb/chroma:1.5.2
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/data
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
      # Enable Authentication
      - CHROMA_SERVER_AUTH_PROVIDER=${CHROMA_SERVER_AUTH_PROVIDER}
      - CHROMA_SERVER_AUTH_CREDENTIALS=${CHROMA_SERVER_AUTH_CREDENTIALS}
      - CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER=${CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER}  
  redis:
    image: redis:7-alpine
    # The --port flag tells Redis to listen on the injected $PORT
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${PORT:-6379} --appendonly yes    
    ports: 
      - "6379:6379"
    volumes:
      - ./redis_data:/data
  digitaltwin-api-service:
    build: 
      context: .
      dockerfile: Dockerfile-local
    command: uv run python src/RestService.py
    image: digital_twin_service
    env_file: 
      - .env
      - .env.shared
    ports:
      - "8080:8080" 
    volumes:
      - ./logs:/app/logs
      # - ./config/system.yaml:/app/config/system.yaml:ro
      - ./data:/app/data
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO} # Use the variable if it exists
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
    depends_on:
      - chromadb
      - redis
  # The Embedded Face (Gradio)
  digitaltwin-ui:
    build: 
      context : .
      dockerfile: Dockerfile-local
    image: digital_twin_ui
    env_file: 
      - .env
      - .env.shared
    command: uv run python src/GradioUI.py
    ports:
      - "7860:7860"
    environment:
      - UI_SETTINGS__CHAT_SERVICE_URL=http://digitaltwin-api-service:8080/chat
    depends_on:
      - digitaltwin-api-service
  # chroma-admin:
  #   image: fengzhichao/chromadb-admin:latest
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     # Use the SERVICE NAME 'chromadb' here, not localhost
  #     - CHROMA_URL= http://172.18.0.2:8000
  #   depends_on:
  #     - chromadb